# Site settings
title: Tableau Web Data Connector
email: jdominguez@tableau.com
description: Connect to your web data from Tableau.
baseurl: "/webdataconnector"
# permalink: pretty
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
    toc_levels: 1..3

# Exclude
exclude: ['node_modules']

